import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/ui/CustomCursor";
import GlobalAnimations from "@/components/ui/GlobalAnimations";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Belmont Publishing",
  description: "Generated By Belmont Developers",
  icons: {
    icon: "/images/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col"
        style={{ fontFamily: "Raleway, Arial, sans-serif" }}
      >
        <CustomCursor />
        <GlobalAnimations />
        {children}
      </body>
    </html>
  );
}